FROM registry.redhat.io/rhel10/rhel-bootc:10.0-1750161981

RUN useradd -m -s /bin/bash Arm && \
	echo 'Arm:pass' | chpasswd

RUN echo 'root:pass' | chpasswd

RUN dnf install -y lm_sensors && \
	dnf clean all
